### ISSUE TITLE
Version of mitsuba required for render-engine branch

### ISSUE THREAD

**Issue by akonneker** [mitsuba-renderer/mitsuba2-blender#10]
Thank you for the great work!

I'm trying to use the render-engine branch, since it seems to support converting blender scenes into mitsuba dictionaries (as opposed to xml files), which I am trying to do in a headless blender script.

Which branch of the mitsuba2 repo are you working against? I tried the [blender-refactoring branch](https://github.com/mitsuba-renderer/mitsuba2/tree/blender_refactoring) but I'm unable to import mitsuba in python after building it, due to an import error with enoki. Can you point me in the right direction?

**Comment by bathal1** [comment]
Hi,

The `render_engine` branch of the addon indeed uses mitsuba's `blender-rafactoring` branch (which should be merged to `next`shortly). You should be able to use it.

Can you please share your setup as well as the errors you get when trying to use it?

**Comment by akonneker** [comment]
I am using blender 2.92, with the bundled python swapped out for a conda environment on ubuntu 20.04.
However, I'm unable to reproduce my own error from earlier. A reboot seems to have fixed it, so it may have been an issue with my environment variables?

I did have an issue with the rendering aspect of the add-on, which throws this error with my simple test scene:
```
Read prefs: ~/.config/blender/2.92/config/userpref.blend
Read blend: ~/Documents/models/test_scenes/cornell-ish_box.blend
2021-03-10 11:02:16 INFO  py00  [export_context.py:129] log(): Ignoring Blender's default background...
Python: Traceback (most recent call last):
  File "~/.config/blender/2.92/scripts/addons/mitsuba2-blender-render_engine/engine/final.py", line 44, in render
    self.converter.scene_to_dict(depsgraph)
  File "~/.config/blender/2.92/scripts/addons/mitsuba2-blender-render_engine/export/convert.py", line 76, in scene_to_dict
    export_object(object_instance, self.export_ctx, evaluated_obj.name in particles)
  File "~/.config/blender/2.92/scripts/addons/mitsuba2-blender-render_engine/export/geometry.py", line 99, in export_object
    mat_nr)
  File "~/.config/blender/2.92/scripts/addons/mitsuba2-blender-render_engine/export/geometry.py", line 40, in convert_mesh
    props['uvs'] = uv_layer.data[0].as_pointer()
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

location: <unknown location>:-1
```

This might deserve its own issue, though.

**Comment by bathal1** [comment]
Great to hear. Can you open a new issue and also include the scene causing it so I can investigate? Looks like you're trying to export meshes with no UVs, and there are no checks for that.

I'm closing this issue.

**Comment by ALLIESXO** [comment]
@bathal1 
When downloading the .zip file from the [**release list**](https://github.com/mitsuba-renderer/mitsuba2-blender/releases) the naming of the zip is "mitsuba2-blender-0.1.zip" by default, which leads to the error of this issue.
When downloading the zip file from master branch the naming is different so no errors occur. 

In order to avoid this issue in future, the releases should have a different version naming (without dot in between).
