### ISSUE TITLE
Unable to import mitsuba

### ISSUE THREAD

**Issue by A-guridi** [mitsuba-renderer/mitsuba2-blender#11]
Hello,

I have followed all the instructions to install mitsuba 2.2.1 and install the add-on. However, when I try to run the export, it fails just at the start with an import error, unable to import mitsuba.

The thing is, I have run some python scripts where I'm able to import mitsuba without any problem. This error only happens when executing the code inside the blender API. However, I believe this is the only method right now to export it. Is it possible to run the export files without needing to run it from the Blender environment ?

From the error file I get that mistuba was compiled in a different python environment as blender, but I guess that should be normal, since Mitsuba was compiled following a virtual conda environment and blender is always compiled following the blender compiler. Still, since mitsuba is in PATH, I guess Blender should find it ?

These are my system specifications:

Ubuntu 20.4
Python 3.8
Mitsuba 2.2.1
Blender 2..8.3 -2.9.3 ( I tried two separate versions but none worked )

The PATH variable is pointing to both:
`home/ubuntu/mitsuba2/build`
`home/ubuntu/mitsuba2/build/dist`

and PYTHONPATH to:
`home/ubuntu/mistuba2/build/dist/python`

**Comment by merlinND** [comment]
Hello @A-guridi,

Please check the first line of this repository's README: https://github.com/mitsuba-renderer/mitsuba2-blender/blob/master/README.md#how-to-install-the-add-on

The Python major versions must match. After a quick check on my machine, it looks like Blender 2.90.1 uses Python 3.7.7, but you compiled with Python 3.8. You can check the specific Python version used by your Blender by opening a Python terminal in Blender.
