### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by G-nn-r** [mitsuba-renderer/mitsuba2-blender#18]
Hello,

Mitsuba2 itself has a license included into the repository ([link](https://github.com/mitsuba-renderer/mitsuba2/blob/master/LICENSE)), but the Blender add-on has no license at all.

Therefore, it would be really great if a license could be added to this project (either the same license as in the main mitsuba2 project or a similar license that allows usage under certain conditions (e.g., MIT)).

Without any license, the default copyright laws apply, which means that the usage of the source code is very limited (see [GitHub documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license)). This vague specification creates a difficult situation for possible users, especially (but not only) for usage in the context of commercial projects.

Thank you very much!

**Comment by bathal1** [comment]
Done.
