### ISSUE TITLE
Why my exported materials are not right!

### ISSUE THREAD

**Issue by HsiangYangChu** [mitsuba-renderer/mitsuba2-blender#19]
I try to you this add-on to invert the blender file to the mitsuba. It seems there is something wrong with this invention.
The following is the [blender](https://cloud.tsinghua.edu.cn/f/ec346c7bfe6d4ba7ab4c/?dl=1) file and the exported [mitsuba](https://cloud.tsinghua.edu.cn/f/c75d14d1f9d54813ac79/?dl=1) file.
Looking forward to your reply!

**Comment by bathal1** [comment]
Hello,

Not all materials you can create in Blender are supported in the exporter, as many shader nodes do not have an equivalent in Mitsuba. The README lists the supported BSDFs.

Currently, the Disney BSDF is not supported in Mitsuba, so you cannot export such nodes. If you  want to export this scene, you need to modify it to use supported materials.

If you have trouble exporting a scene, I recommend you look at the export logs, which should be pretty verbose. They should be printed to the console. If you are on windows, you need to enable it in blender (Window > Toggle system console), on macOS or linux, you need to launch blender from the command line.
