### ISSUE TITLE
[Win7 x64bit] Mitsuba2.1 build for Blender 2.82a

### ISSUE THREAD

**Issue by odil24** [mitsuba-renderer/mitsuba2-blender#4]
Hi there. is somebody can paste here Windows build of Mitsuba2.1 for Blender 2.82a or 2.90?

here my mail:
odikhanyakubov@gmail.com

Thanks.

**Comment by Speierers** [comment]
Hi @odil24 ,

You should be able to compile Mitsuba 2 yourself. Have a look at the documentation for step by step instructions.

I will close this as it is not an issue.
