### ISSUE TITLE
Plugin "blender" not found on attempting to export scene

### ISSUE THREAD

**Issue by gianlucaagresti** [mitsuba-renderer/mitsuba2-blender#6]
Hello everyone,
I installed the plugin on Blender 2.82 and I manually added the the path to Mitsuba 2 build (dist folder;  I have no MITSUBA_DIR in my environment). 

However, when I try to export a  scene I have the following error message.

![image](https://user-images.githubusercontent.com/10243998/85369377-4f7d7800-b52d-11ea-88ad-9596268aa380.png)

Do you think this could be related to the Mitsuba 2 build? 

This happened on a Windows 10 x64 machine. I used Python 3.7 from Anaconda 3 for the build of Mitsuba 2.

Thank you for the support.

**Comment by Speierers** [comment]
Did you run `setpath.bat` as stated in the documentation?

**Comment by gianlucaagresti** [comment]
Yes, but MITSUBA_DIR was not added to the path even if I ran it as administrator

**Comment by bathal1** [comment]
Hi,
If you get this error message, I'm assuming you were able to click on **export** -> **Mitsuba 2** and this happened during the export, is this correct?
It looks like the Addon can find Mitsuba 2, but fails to find a specific plugin, used to convert meshes. Can you please check that your Mitsuba 2 repository is up to date with the latest master, and that you compiled it recently?

**Comment by gianlucaagresti** [comment]
Hello,
1) Yes, I can click on export -> Mitsuba 2 and the error happened during the export.
2) The error log above was obtained with Mitsuba 2.1.0 and Mitsuba 2 Blender master.

If I test Mitsuba 2 master with Mitsuba 2 Blender master, I have a different error. It seems that it is not possible to locate a dll:
![image](https://user-images.githubusercontent.com/10243998/85527447-2c28fa80-b60b-11ea-8a21-32009a087a2c.png)

I used as "Build path" mitsuba2-master\build\, that is where I built the sfotware.

Best regards,
Gianluca

**Comment by bathal1** [comment]
The Blender plugin was merged after the 2.1.0 release, which explains the first error message. 
The second one is odd, did you remove 'scalar_rgb' from the list of enabled variants in `mitsuba.conf` ?

**Comment by gianlucaagresti** [comment]
Ok, thank you for the support.
At the end, I am able to export the Blender scene. 
My issue was that, I was still using Mitsuba 2.1.0 python package in Blender even if I was referring to the Mitsuba 2 master executable.

Best regards,
Gianluca
